# Generated by Django 5.2.5 on 2026-01-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyscan',
            name='undertone',
            field=models.CharField(choices=[('warm', 'Warm'), ('cool', 'Cool')], default='warm', max_length=10),
        ),
        migrations.AlterField(
            model_name='bodyscan',
            name='skin_tone',
            field=models.CharField(choices=[('very_light', 'Very Light'), ('light', 'Light'), ('intermediate', 'Intermediate'), ('tan', 'Tan'), ('dark', 'Dark')], max_length=15),
        ),
    ]
