# Generated by Django 4.2.7 on 2026-02-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_system', '0003_bodyscan_arm_length_bodyscan_body_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyscan',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyscan',
            name='is_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
