# Generated by Django 4.2.7 on 2026-03-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_system', '0006_merge_20260225_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
    ]
