# Generated by Django 4.2.7 on 2026-03-01 20:58

from django.db import migrations, models
import fitting_system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_system', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=fitting_system.storage.ProductImageStorage(), upload_to='images/products/'),
        ),
    ]
