# Generated by Django 4.2.7 on 2026-03-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_system', '0008_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fit_type',
        ),
    ]
